name: Update BioSimulators command-line interface and Docker image

on:
  release:
    types:
      - published

jobs:
  updateBioSimulatorsCliAndDockerImage:
    name: Trigger the building and release of the BioSimulators version of OpenCOR
    runs-on: ubuntu-latest
    env:
      # Owner/repository-id for the GitHub repository for the downstream command-line interface and Docker image
      DOWNSTREAM_REPOSITORY: biosimulators/Biosimulators_OpenCOR

      # Username/token to use the GitHub API to trigger an action on the GitHub repository for the downstream
      # command-line interface and Docker image. Tokens can be generated at https://github.com/settings/tokens.
      # The token should have the scope `repo`
      GH_ISSUE_USERNAME: ${{ secrets.GH_ISSUE_USERNAME }}
      GH_ISSUE_TOKEN: ${{ secrets.GH_ISSUE_TOKEN }}
    steps:
      - name: Trigger a GitHub action that will build and release the BioSimulators version of OpenCOR
        run: |
          PACKAGE_VERSION="${GITHUB_REF/refs\/tags\//}"
          WORKFLOW_FILE=ci.yml

          curl \
            -X POST \
            -u ${GH_ISSUE_USERNAME}:${GH_ISSUE_TOKEN} \
            -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${DOWNSTREAM_REPOSITORY}/actions/workflows/${WORKFLOW_FILE}/dispatches \
            -d "{\"inputs\": {\"simulatorVersion\": \"${PACKAGE_VERSION}\", \"simulatorVersionLatest\": \"true\"}}"
