name: Release Docker image

on:
  release:
    types:
      - published

jobs:
  release-docker-image:
    name: Release Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          # See https://docs.docker.com/ci-cd/github-actions/#set-up-a-docker-project
          # for instructions on how to create secrets for Docker Hub.
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Get the version of the Docker image
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: opencor/opencor:latest,opencor/opencor:${{ steps.get_version.outputs.VERSION }}
